apiVersion: v1
kind: Pod
metadata:
  name: client-pod
  labels:
    # label name is arbitrary as long as match servivce selector 
    component: web
spec:
  containers:
    - name: client
      image: stephengrider/multi-worker
      # cannot be changed once created
      ports:
        - containerPort: 3000
# kubectl apply -f $FILENAME