apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  # deployment create replicas set
  replicas: 1
  selector:
    matchLabels:
      component: web
  # pod configuration
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:    
      - name: client
        image: stephengrider/multi-client
        ports:
          - containerPort: 3000