apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  # deployment create replicas set
  replicas: 1
  selector:
    matchLabels:
      component: web
  # pod configuration
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:    
      - name: client
        # update image with command $kubectl set image deployment/client-deployment client=stephengrider/multi-client:v5
        image: stephengrider/multi-client
        ports:
          - containerPort: 3000
# set docker client to minikube docker engine: $eval $(minikube docker-env)